services:
  db:
    image: postgres:17.5-alpine
    restart: always
    environment:
      POSTGRES_DB: ETL basic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./tables/promocao.sql:/docker-entrypoint-initdb.d/promocao.sql

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python scheduler.py